# Generated by Django 5.1.3 on 2024-11-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bankloan',
            fields=[
                ('Loan_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Loan_Type', models.CharField(max_length=30)),
                ('Loan_Amt', models.IntegerField()),
                ('cust_accno', models.IntegerField()),
                ('cust_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
